
  CREATE TABLE "ASISTENCIA" 
   (	"ID_ASIST" NUMBER, 
	"ID_EST" NUMBER NOT NULL ENABLE, 
	"FECHA_ASIST" DATE NOT NULL ENABLE, 
	"ESTADO" VARCHAR2(10) NOT NULL ENABLE, 
	"OBSERVACION" VARCHAR2(200), 
	 PRIMARY KEY ("ID_ASIST")
  USING INDEX  ENABLE, 
	 CONSTRAINT "CK_ASIST_ESTADO" CHECK (ESTADO IN ('PRESENTE','AUSENTE','TARDE')) ENABLE, 
	 CONSTRAINT "UQ_ASIST_EST_FECHA" UNIQUE ("ID_EST", "FECHA_ASIST")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "ASISTENCIA" ADD CONSTRAINT "FK_ASIST_EST" FOREIGN KEY ("ID_EST")
	  REFERENCES "ESTUDIANTE" ("ID_EST") ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "BI_ASISTENCIA" 
BEFORE INSERT ON ASISTENCIA
FOR EACH ROW
BEGIN
  IF :NEW.ID_ASIST IS NULL THEN
    SELECT ASISTENCIA_SEQ.NEXTVAL
      INTO :NEW.ID_ASIST
      FROM DUAL;
  END IF;

  :NEW.FECHA_ASIST := TRUNC(:NEW.FECHA_ASIST);
END;
/
ALTER TRIGGER "BI_ASISTENCIA" ENABLE;