INSERT INTO ESTUDIANTE (ID_EST, NOMBRE, CORREO, ACTIVO) VALUES (1, 'Ana Pérez',    'ana.perez@example.com',   'S');
INSERT INTO ESTUDIANTE (ID_EST, NOMBRE, CORREO, ACTIVO) VALUES (2, 'Bruno García', 'bruno.garcia@example.com','S');
INSERT INTO ESTUDIANTE (ID_EST, NOMBRE, CORREO, ACTIVO) VALUES (3, 'Carla López',  'carla.lopez@example.com', 'S');
INSERT INTO ASISTENCIA (ID_ASIST, ID_EST, FECHA_ASIST, ESTADO, OBSERVACION)
VALUES (1, 1, TRUNC(SYSDATE) - 2, 'PRESENTE', 'Asistió puntual');
INSERT INTO ASISTENCIA (ID_ASIST, ID_EST, FECHA_ASIST, ESTADO, OBSERVACION)
VALUES (2, 2, TRUNC(SYSDATE) - 2, 'AUSENTE',  'Sin justificar');
INSERT INTO ASISTENCIA (ID_ASIST, ID_EST, FECHA_ASIST, ESTADO, OBSERVACION)
VALUES (3, 3, TRUNC(SYSDATE) - 2, 'TARDE',    'Llegó 15 minutos tarde');
INSERT INTO ASISTENCIA (ID_ASIST, ID_EST, FECHA_ASIST, ESTADO, OBSERVACION)
VALUES (4, 1, TRUNC(SYSDATE) - 1, 'PRESENTE', null);
INSERT INTO ASISTENCIA (ID_ASIST, ID_EST, FECHA_ASIST, ESTADO, OBSERVACION)
VALUES (5, 2, TRUNC(SYSDATE) - 1, 'PRESENTE', null);
INSERT INTO ASISTENCIA (ID_ASIST, ID_EST, FECHA_ASIST, ESTADO, OBSERVACION)
VALUES (6, 3, TRUNC(SYSDATE),     'AUSENTE',  'Enfermedad reportada');
