
  CREATE TABLE "ESTUDIANTE" 
   (	"ID_EST" NUMBER, 
	"NOMBRE" VARCHAR2(100) NOT NULL ENABLE, 
	"CORREO" VARCHAR2(120) NOT NULL ENABLE, 
	"ACTIVO" CHAR(1) NOT NULL ENABLE, 
	 CONSTRAINT "UQ_EST_CORREO" UNIQUE ("CORREO")
  USING INDEX  ENABLE, 
	 CONSTRAINT "CK_EST_ACTIVO" CHECK (ACTIVO IN ('S','N')) ENABLE, 
	 PRIMARY KEY ("ID_EST")
  USING INDEX  ENABLE
   ) ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "BI_ESTUDIANTE" 
BEFORE INSERT ON ESTUDIANTE
FOR EACH ROW
 WHEN (NEW.ID_EST IS NULL) BEGIN
  SELECT ESTUDIANTE_SEQ.NEXTVAL
    INTO :NEW.ID_EST
    FROM DUAL;
END;
/
ALTER TRIGGER "BI_ESTUDIANTE" ENABLE;